version: "3"

services:
  backend:
    build:
      context: ./services/backend
    depends_on:
      - db
    env_file: ./services/backend/.env
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./services/backend:/usr/src/app

  frontend:
    build:
      context: ./services/frontend
    command: yarn dev
    depends_on:
      - db
      - backend
      - authentication
    volumes:
      - ./services/frontend:/usr/src/app
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"

  authentication:
    build:
      context: ./services/authentication
    command: yarn dev
    env_file: ./services/authentication/.env
    depends_on:
      - db
    ports:
      - "3030:3030"
    volumes:
      - ./services/authentication:/usr/src/app
      - "/usr/src/app/node_modules"

  db:
    image: postgres:11.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
