version: "3"

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    env_file: ./backend/.env
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./backend:/backend-app

  frontend:
    build:
      context: ./frontend
    command: yarn dev
    depends_on:
      - db
      - backend
      - authentication
    volumes:
      - ./frontend:/frontend-app
    ports:
      - "3000:3000"

  authentication:
    build:
      context: ./authentication
    command: yarn dev
    env_file: ./authentication/.env
    depends_on:
      - db
    ports:
      - "3030:3030"
    volumes:
      - ./authentication:/authentication-app

  db:
    image: postgres:11.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
